### ISSUE TITLE
Responsive dashboard layout and dashboard page implementation

### ISSUE THREAD

**Issue by youngancient** [groupxilabs/Ikigai#5]

**Comment by youngancient** [comment]
![Screenshot from 2024-11-26 14-05-59](https://github.com/user-attachments/assets/adc634eb-c0f4-44fa-ad6c-5f92e42857da)

- The mobile dropdown length should be longer like fit 100vh of mobile.
- Clicking the right side which is transparent should also close the modal (I have created an OutsideClickWrapper component that handles stuff like that)
- When a user clicks the logo, it should navigate them back to the homepage (like how the desktop logo works)

**Comment by collinsadi** [comment]
done
